name: weather
description: A command-line application for fetching your local weather.
version: 1.0.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  yaml: ^2.2.1
  http: ^0.12.2
  path: ^1.7.0
  args: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
