name: weather
description: An API for OpenWeather's API suite.
version: 1.0.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  args: ^1.6.0
  open_weather:
    git: https://github.com/Luckey-Elijah/open_weather.git
  

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
